Часть 3.1 частично сделана
Nemexur/Econometrics pull request #2
Opened 2019-04-28 12:00 UTC by glendawur

В описательном анализе:
-в Task 3 добавлены команды по описательному анализу (sum/tab) и команды построения графиков
- создан master.do
- в гугл доке с отчетом добавлены рисунки графиков и данные по числовым переменным (miscval,  saleprice)

2019-04-28 17:01 UTC, Nemexur requested changes

2019-04-28 17:01 UTC, Nemexur commented on Task 3.do
> +tab mssubclass
Добавь, пожалуйста, ниже комментов побольше. Препод просил больше комментить. Типа: "Graph Bars for varibles". Что-то подобное

2019-04-28 17:01 UTC, Nemexur commented on master.do
> +*	 Member of the project team (names): Smetanin Ilya, Milogradskiy Alexnadr, Rykov Andrei
Alexnadr

2019-04-29 18:27 UTC, glendawur commented
Completed 3.1

2019-04-29 18:32 UTC, Nemexur requested changes

2019-04-29 18:32 UTC, Nemexur commented on master.do
> +*	 miscfeature 	  		Miscellaneous feature not covered in other categories
Добавь сюда ещё описание GrLivArea и GarageArea

2019-04-29 19:05 UTC, Nemexur approved these changes

2019-04-29 19:06 UTC, merged

2019-04-29 19:41 UTC, Nemexur commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать раздел 3.1](https://trello.com/c/ecwQmCg6/22-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB-31)